-- liquibase formatted sql

-- changeset kerher:1
create table if not exists users
(
    id bigint generated by default as identity primary key,
    username varchar(24) not null unique,
    role varchar (10) not null
);